#!/usr/bin/env bash
# Configure Nginx to add a custom HTTP response header

# Update package list and install nginx if not installed
apt-get update
apt-get install -y nginx

HOSTNAME=$(hostname)

# Configure Nginx to add custom header
sed -i "/server_name _;/a \    add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

# Restart Nginx to show the changes
service nginx restart
