#!/usr/bin/env bash
#Bash script that installs HAProxy & makes configurations

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5819-webs
    bind *:80
    mode http
    balance roundrobin
    server 7041-web-01 18.234.240.227:80 check
    server 7041-web-02 44.204.30.8:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
