#!/usr/bin/env bash
# Install and configure HAproxy load balancer

# Update package list and install HAproxy
apt-get update
apt-get install -y haproxy

# Backup original config
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Configuring HAproxy
cat >> /etc/haproxy/haproxy.cfg <<EOF

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    mode http
    server 7041-web-01 18.234.240.227:80 check
    server 7041-web-02 44.204.30.8:80 check
EOF

# Enabling HAproxy script
echo "ENABLED=1" > /etc/default/haproxy

service haproxy restart
