#!/usr/bin/env bash
# Configures nginx with a 301 redirect for /redirect_me

apt-get update -y
apt-get install -y nginx

cat > /etc/nginx/sites-available/default << 'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

echo 'Holberton School for the win!' > /var/www/html/index.html
service nginx restart
